// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcbTsySsB-x5qlma8pkeFwbSP1ORVWBbE',
    appId: '1:176088517890:android:8bced881bb68c96791861b',
    messagingSenderId: '176088517890',
    projectId: 'tengri-app',
    storageBucket: 'tengri-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPLV8oLmpjA-HPuirJCLe8U2H4J04tJZU',
    appId: '1:176088517890:ios:a9553ad4dd98c16891861b',
    messagingSenderId: '176088517890',
    projectId: 'tengri-app',
    storageBucket: 'tengri-app.appspot.com',
    iosBundleId: 'com.mrblab.primelms',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBDuLCSehApVZp2Bd4nS89BgCeX77ChPk4",
    authDomain: "tengri-app.firebaseapp.com",
    projectId: "tengri-app",
    storageBucket: "tengri-app.appspot.com",
    messagingSenderId: "176088517890",
    appId: "1:176088517890:web:9d931d610bae6e2891861b",
    measurementId: "G-ZMK3RDZ0Y7"
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPLV8oLmpjA-HPuirJCLe8U2H4J04tJZU',
    appId: '1:176088517890:ios:cf8e604ff023dae991861b',
    messagingSenderId: '176088517890',
    projectId: 'tengri-app',
    storageBucket: 'tengri-app.appspot.com',
    iosBundleId: 'com.mrblab.lmsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDuLCSehApVZp2Bd4nS89BgCeX77ChPk4',
    appId: '1:176088517890:web:0e1d4ec8be47aca491861b',
    messagingSenderId: '176088517890',
    projectId: 'tengri-app',
    authDomain: 'tengri-app.firebaseapp.com',
    storageBucket: 'tengri-app.appspot.com',
    measurementId: 'G-FBEQM6D9JC',
  );

}