// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCGOV_u7_cUrjY02WfXUzUNijvqoe0oKp0",
    authDomain: "tengrilmsapp.firebaseapp.com",
    databaseURL: "https://tengrilmsapp-default-rtdb.firebaseio.com",
    projectId: "tengrilmsapp",
    storageBucket: "tengrilmsapp.appspot.com",
    messagingSenderId: "1044827531726",
    appId: "1:1044827531726:web:e0050a167454cdb62f639f",
    measurementId: "G-HL59VJQQL7"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPLV8oLmpjA-HPuirJCLe8U2H4J04tJZU',
    appId: '1:176088517890:ios:9ebf8d6b4f52d11c91861b',
    messagingSenderId: '176088517890',
    projectId: 'tengri-app',
    storageBucket: 'tengri-app.appspot.com',
    iosBundleId: 'com.tengri.lms_app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcbTsySsB-x5qlma8pkeFwbSP1ORVWBbE',
    appId: '1:176088517890:android:78c34ead8d56744591861b',
    messagingSenderId: '176088517890',
    projectId: 'tengri-app',
    storageBucket: 'tengri-app.appspot.com',
  );

}